#!/bin/bash

#SBATCH -A m2qm-efrc
#SBATCH --qos=m2qm-efrc-b
#SBATCH -p hpg-default
#SBATCH -J Spin
#SBATCH -t 1-00:00:00
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 2
#SBATCH --mem=4Gb
#SBATCH --error=tmp.error.%j
#SBATCH --output=tmp.output.%j
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shlufl@ufl.edu
##SBATCH --dependency=afterok:17691116

source ~/.bash_aliases; keep_log

python main.py > quantum_master_lambda0_thetaB90_0.0001.log

